# Loggers for Websites
ZEENWOMAN_LOGGER = "zeenwoman"
WOVWORLD_LOGGER = "wovworld"
SULFAH_LOGGER = "sulafah"
SPUTNIK_LOGGER = "sputnik"
SPEEDSPORTS_LOGGER = "speedsports"
SHEEPOFFICIAL_LOGGER = "sheepofficial"
SHAFFER_LOGGER = "shaffer"
SAPPHIRE_LOGGER = "sapphire"
SAYA_LOGGER = "saya"
SANASAFINAZ_LOGGER = "sanasafinaz"
SAEEDGHANI_LOGGER = "saeedghani"